---
- name: Install MySql
  hosts: webservers
  become: yes

  vars:
    some_variable: some_value

  tasks:
  - name: Install mysql
    apt:
      name: mysql-server
      state: present

  - name: Install httpd
    apt:
      name: apache2
      state: present